language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t cristianlaurini/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cristianlaurini/multi-docker-test npm run test

after_success:
    - docker build -t cristianlaurini/multi-client ./client
    - docker build -t cristianlaurini/multi-nginx ./nginx
    - docker build -t cristianlaurini/multi-server ./server
    - docker build -t cristianlaurini/multi-worker ./worker
    # Login in the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push cristianlaurini/multi-client
    - docker push cristianlaurini/multi-nginx
    - docker push cristianlaurini/multi-server
    - docker push cristianlaurini/multi-worker

deploy:
    provide: elasticbeanstalk
    region: "eu-west-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-497881757044"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY